export const tagTitle = {
  cse: "Computer Science & Engineering",
  eee: "Electrical and Electronics Engineering",
  math: "Mathematics",
  sta: "Statistics",
  acce: "Applied Chemistry and Chemical Engineering",
  accounting: "Accounting",
  agriculture: "Agriculture",
  agroprocess: "Food and Agroprocess Engineering",
  architecture: "Architecture",
  biochemistry: "Biochemistry and Molecular Biology",
  botany: "Botany",
  chemistry: "Chemistry",
  civil: "Civil Engineering",
  economics: "Economics",
  english: "English",
  environmental: "Environmental Science & Disaster Management",
  finance: "Finance and Banking",
  fisheries: "Fisheries and Marine Bioscience",
  genetic: "Biotechnology and Genetic Engineering",
  history: "History",
  ir: "International Relations",
  law: "Law",
  management: "Management Studies",
  marketing: "Marketing",
  pharmacy: "Pharmacy",
  physics: "Physics",
  political: "Political Science",
  psychology: "Psychology",
  sociology: "Sociology",
  tourism: "Tourism and Hospitality Management",
  veterinary: "Animal Science and Veterinary Medicine",
  islamic: "Islamic",
  nonacademic: "Non Academic",
};
